version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=pomodorogo-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  pomodorogo-server:
    container_name: pomodorogo-server
    restart: always
    environment:
      DB_HOST: postgres
      DB_NAME: pomodorogo-server
      DB_USER: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8500:8500